### ISSUE TITLE
Houndigrade is not writing results to the sqs queue.

### ISSUE THREAD

**Issue by ilyavw** [cloudigrade/houndigrade#33]
## Summary

After launching an ecs task to inspect images I expect houndigrade to write the results to the sqs queue. Houndigrade happily exits, but not message is written.

## Steps to Reproduce

1. Add a new account and have cloudigrade do all prep and kick off an inspection job
2. Watch houndigrade task finish

## Expected Result

- There is a results payload in the namespace-inspection_results queue that can be picked up by the celery task to process it

## Actual Result

- There is no payload, or queue to match that name, even though it should be auto-created.

**Comment by kholdaway** [comment]
I have done this several times and it is working now.
